- hosts: terraform-ansible
  tasks: 
  - name: Instalando o python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes

  - name: Instalando dependências com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework

  - name: Verificando se o projeto já existe
    stat: 
      path: /home/ubuntu/tcc/setup/settings.py
    register: projeto

  - name: Iniciando projeto Django
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
    when: not projeto.stat.exists
    ignore_errors: yes

  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regex: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

  - name: Executando projeto Django
    shell: '. /home/ubuntu/tcc/venv/bin/activate; cd /home/ubuntu/tcc; python manage.py runserver 0.0.0.0:8000 >/dev/null 2>&1 &'
    async: 10
    poll: 0